// DO NOT EDIT.
// Generated by protoc-gen-wtcrdt (tools/protoc-gen-wtcrdt) from the wt.crdt and buf.validate
// options in proto/; regenerate with `make -C tools/protoc-gen-wtcrdt generate`.
package com.villagecompute.wiretuner.crdt.schema;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.util.List;
import java.util.Map;

/**
 * The merge table (docs/spec/crdt-model.adoc, "Merge policies"): for every message reachable
 * from NodeProps, CommonProps and Node, the effective merge policy of each field.  {@link
 * #json()} is the serialized table the server sends in {@code Welcome.merge_table}.
 */
public final class MergeTable {
  /** How concurrent writes to a field are reconciled (wt.crdt.Merge without its prefix). */
  public enum Policy { ATOMIC, STRUCT, SEQUENCE, TEXT, SET, VARIANT }

  /** What a NodeRef reads as while its target is deleted or unknown (wt.crdt.RefFallback). */
  public enum RefFallback { UNSET, CACHED, PLACEHOLDER }

  /**
   * One row: the effective policy of one field.  {@code typeName}, {@code elementMessage} and
   * {@code oneof} are null when they do not apply.
   */
  public record FieldPolicy(
      int fieldNumber,
      String name,
      Policy policy,
      RefFallback onDangling,
      boolean localOnly,
      String type,
      boolean repeated,
      String typeName,
      String elementMessage,
      String oneof) {}

  /** The rows of one message, keyed by field number. */
  public record MessagePolicy(String name, Map<Integer, FieldPolicy> fields) {}

  /** A MERGE_VARIANT message: its kind discriminator and the message fields holding each case. */
  public record VariantPolicy(int kindField, List<Integer> caseFields) {}

  /** SHA-256 (hex) of the canonical JSON table without its version key. */
  public static final String VERSION = "d6cf77d86d213a1fceaab3b6cfa91df6c0ae2673e43a2023c8d03a4b45b05090";

  /** The name of the JSON resource beside this class. */
  public static final String RESOURCE = "merge-table.json";

  /** The rows of every message, by fully qualified proto name. */
  public static final Map<String, MessagePolicy> MESSAGES =
      Map.ofEntries(
          Map.entry("wiretuner.doc.v1.CommonProps", table_wiretuner_doc_v1_CommonProps()),
          Map.entry("wiretuner.doc.v1.DataBinding", table_wiretuner_doc_v1_DataBinding()),
          Map.entry("wiretuner.doc.v1.DocumentProps", table_wiretuner_doc_v1_DocumentProps()),
          Map.entry("wiretuner.doc.v1.ElementId", table_wiretuner_doc_v1_ElementId()),
          Map.entry("wiretuner.doc.v1.GroupProps", table_wiretuner_doc_v1_GroupProps()),
          Map.entry("wiretuner.doc.v1.Halftone", table_wiretuner_doc_v1_Halftone()),
          Map.entry("wiretuner.doc.v1.LayerProps", table_wiretuner_doc_v1_LayerProps()),
          Map.entry("wiretuner.doc.v1.MasterPageProps", table_wiretuner_doc_v1_MasterPageProps()),
          Map.entry("wiretuner.doc.v1.NavigationProps", table_wiretuner_doc_v1_NavigationProps()),
          Map.entry("wiretuner.doc.v1.Node", table_wiretuner_doc_v1_Node()),
          Map.entry("wiretuner.doc.v1.NodeProps", table_wiretuner_doc_v1_NodeProps()),
          Map.entry("wiretuner.doc.v1.NodeRef", table_wiretuner_doc_v1_NodeRef()),
          Map.entry("wiretuner.doc.v1.OpId", table_wiretuner_doc_v1_OpId()),
          Map.entry("wiretuner.doc.v1.PageProps", table_wiretuner_doc_v1_PageProps()),
          Map.entry("wiretuner.doc.v1.SettingsProps", table_wiretuner_doc_v1_SettingsProps()),
          Map.entry("wiretuner.doc.v1.TextWrap", table_wiretuner_doc_v1_TextWrap()),
          Map.entry("wiretuner.doc.v1.Transform", table_wiretuner_doc_v1_Transform())
      );

  /** The MERGE_VARIANT messages, by fully qualified proto name. */
  public static final Map<String, VariantPolicy> VARIANTS =
      Map.ofEntries(
      );

  private MergeTable() {}

  /** The row for one field, or null when the message or field is not in the table. */
  public static FieldPolicy field(String message, int fieldNumber) {
    MessagePolicy m = MESSAGES.get(message);
    return m == null ? null : m.fields().get(fieldNumber);
  }

  /** The serialized table, UTF-8 JSON, exactly as {@code Welcome.merge_table} carries it. */
  public static byte[] json() {
    try (InputStream in = MergeTable.class.getResourceAsStream(RESOURCE)) {
      if (in == null) {
        throw new IllegalStateException(RESOURCE + " is not on the classpath beside MergeTable");
      }
      return in.readAllBytes();
    } catch (IOException e) {
      throw new UncheckedIOException(e);
    }
  }

  private static MessagePolicy table_wiretuner_doc_v1_CommonProps() {
    return new MessagePolicy(
        "wiretuner.doc.v1.CommonProps",
        Map.ofEntries(
            Map.entry(1, new FieldPolicy(1, "name", Policy.ATOMIC, RefFallback.UNSET, false, "string", false, null, null, null)),
            Map.entry(2, new FieldPolicy(2, "note", Policy.ATOMIC, RefFallback.UNSET, false, "string", false, null, null, null)),
            Map.entry(3, new FieldPolicy(3, "locked", Policy.ATOMIC, RefFallback.UNSET, false, "bool", false, null, null, null)),
            Map.entry(4, new FieldPolicy(4, "transform", Policy.ATOMIC, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.Transform", null, null)),
            Map.entry(5, new FieldPolicy(5, "canvas", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.NodeRef", null, null)),
            Map.entry(6, new FieldPolicy(6, "url", Policy.ATOMIC, RefFallback.UNSET, false, "string", false, null, null, null)),
            Map.entry(7, new FieldPolicy(7, "style", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.NodeRef", null, null)),
            Map.entry(8, new FieldPolicy(8, "navigation", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.NavigationProps", null, null)),
            Map.entry(9, new FieldPolicy(9, "alt", Policy.ATOMIC, RefFallback.UNSET, false, "string", false, null, null, null)),
            Map.entry(10, new FieldPolicy(10, "decorative", Policy.ATOMIC, RefFallback.UNSET, false, "bool", false, null, null, null)),
            Map.entry(11, new FieldPolicy(11, "halftone", Policy.ATOMIC, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.Halftone", null, null)),
            Map.entry(12, new FieldPolicy(12, "data_binding", Policy.ATOMIC, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.DataBinding", null, null)),
            Map.entry(13, new FieldPolicy(13, "text_wrap", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.TextWrap", null, null)),
            Map.entry(14, new FieldPolicy(14, "origin_layer", Policy.ATOMIC, RefFallback.UNSET, false, "string", false, null, null, null))
        ));
  }

  private static MessagePolicy table_wiretuner_doc_v1_DataBinding() {
    return new MessagePolicy(
        "wiretuner.doc.v1.DataBinding",
        Map.ofEntries(
            Map.entry(1, new FieldPolicy(1, "field", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.ElementId", null, null)),
            Map.entry(2, new FieldPolicy(2, "kind", Policy.ATOMIC, RefFallback.UNSET, false, "enum", false, "wiretuner.doc.v1.BindingKind", null, null))
        ));
  }

  private static MessagePolicy table_wiretuner_doc_v1_DocumentProps() {
    return new MessagePolicy(
        "wiretuner.doc.v1.DocumentProps",
        Map.ofEntries(
            Map.entry(1, new FieldPolicy(1, "common", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.CommonProps", null, null))
        ));
  }

  private static MessagePolicy table_wiretuner_doc_v1_ElementId() {
    return new MessagePolicy(
        "wiretuner.doc.v1.ElementId",
        Map.ofEntries(
            Map.entry(1, new FieldPolicy(1, "counter", Policy.ATOMIC, RefFallback.UNSET, false, "uint64", false, null, null, null)),
            Map.entry(2, new FieldPolicy(2, "replica", Policy.ATOMIC, RefFallback.UNSET, false, "fixed64", false, null, null, null))
        ));
  }

  private static MessagePolicy table_wiretuner_doc_v1_GroupProps() {
    return new MessagePolicy(
        "wiretuner.doc.v1.GroupProps",
        Map.ofEntries(
            Map.entry(1, new FieldPolicy(1, "common", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.CommonProps", null, null))
        ));
  }

  private static MessagePolicy table_wiretuner_doc_v1_Halftone() {
    return new MessagePolicy(
        "wiretuner.doc.v1.Halftone",
        Map.ofEntries(
            Map.entry(1, new FieldPolicy(1, "shape", Policy.ATOMIC, RefFallback.UNSET, false, "enum", false, "wiretuner.doc.v1.HalftoneShape", null, null)),
            Map.entry(2, new FieldPolicy(2, "angle", Policy.ATOMIC, RefFallback.UNSET, false, "double", false, null, null, null)),
            Map.entry(3, new FieldPolicy(3, "frequency", Policy.ATOMIC, RefFallback.UNSET, false, "double", false, null, null, null))
        ));
  }

  private static MessagePolicy table_wiretuner_doc_v1_LayerProps() {
    return new MessagePolicy(
        "wiretuner.doc.v1.LayerProps",
        Map.ofEntries(
            Map.entry(1, new FieldPolicy(1, "common", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.CommonProps", null, null))
        ));
  }

  private static MessagePolicy table_wiretuner_doc_v1_MasterPageProps() {
    return new MessagePolicy(
        "wiretuner.doc.v1.MasterPageProps",
        Map.ofEntries(
            Map.entry(1, new FieldPolicy(1, "common", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.CommonProps", null, null))
        ));
  }

  private static MessagePolicy table_wiretuner_doc_v1_NavigationProps() {
    return new MessagePolicy(
        "wiretuner.doc.v1.NavigationProps",
        Map.ofEntries(
            Map.entry(1, new FieldPolicy(1, "alt", Policy.ATOMIC, RefFallback.UNSET, false, "string", false, null, null, null)),
            Map.entry(2, new FieldPolicy(2, "target", Policy.ATOMIC, RefFallback.UNSET, false, "enum", false, "wiretuner.doc.v1.LinkTarget", null, null)),
            Map.entry(3, new FieldPolicy(3, "go_to_page", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.NodeRef", null, null))
        ));
  }

  private static MessagePolicy table_wiretuner_doc_v1_Node() {
    return new MessagePolicy(
        "wiretuner.doc.v1.Node",
        Map.ofEntries(
            Map.entry(1, new FieldPolicy(1, "id", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.OpId", null, null)),
            Map.entry(2, new FieldPolicy(2, "parent", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.OpId", null, null)),
            Map.entry(3, new FieldPolicy(3, "position", Policy.ATOMIC, RefFallback.UNSET, false, "bytes", false, null, null, null)),
            Map.entry(4, new FieldPolicy(4, "deleted", Policy.ATOMIC, RefFallback.UNSET, false, "bool", false, null, null, null)),
            Map.entry(5, new FieldPolicy(5, "props", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.NodeProps", null, null))
        ));
  }

  private static MessagePolicy table_wiretuner_doc_v1_NodeProps() {
    return new MessagePolicy(
        "wiretuner.doc.v1.NodeProps",
        Map.ofEntries(
            Map.entry(1, new FieldPolicy(1, "document", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.DocumentProps", null, "kind")),
            Map.entry(2, new FieldPolicy(2, "settings", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.SettingsProps", null, "kind")),
            Map.entry(3, new FieldPolicy(3, "page", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.PageProps", null, "kind")),
            Map.entry(4, new FieldPolicy(4, "master_page", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.MasterPageProps", null, "kind")),
            Map.entry(50, new FieldPolicy(50, "group", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.GroupProps", null, "kind")),
            Map.entry(150, new FieldPolicy(150, "layer", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.LayerProps", null, "kind"))
        ));
  }

  private static MessagePolicy table_wiretuner_doc_v1_NodeRef() {
    return new MessagePolicy(
        "wiretuner.doc.v1.NodeRef",
        Map.ofEntries(
            Map.entry(1, new FieldPolicy(1, "id", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.OpId", null, null)),
            Map.entry(2, new FieldPolicy(2, "cached", Policy.ATOMIC, RefFallback.UNSET, false, "bytes", false, null, null, null))
        ));
  }

  private static MessagePolicy table_wiretuner_doc_v1_OpId() {
    return new MessagePolicy(
        "wiretuner.doc.v1.OpId",
        Map.ofEntries(
            Map.entry(1, new FieldPolicy(1, "counter", Policy.ATOMIC, RefFallback.UNSET, false, "uint64", false, null, null, null)),
            Map.entry(2, new FieldPolicy(2, "replica", Policy.ATOMIC, RefFallback.UNSET, false, "fixed64", false, null, null, null))
        ));
  }

  private static MessagePolicy table_wiretuner_doc_v1_PageProps() {
    return new MessagePolicy(
        "wiretuner.doc.v1.PageProps",
        Map.ofEntries(
            Map.entry(1, new FieldPolicy(1, "common", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.CommonProps", null, null))
        ));
  }

  private static MessagePolicy table_wiretuner_doc_v1_SettingsProps() {
    return new MessagePolicy(
        "wiretuner.doc.v1.SettingsProps",
        Map.ofEntries(
            Map.entry(1, new FieldPolicy(1, "common", Policy.STRUCT, RefFallback.UNSET, false, "message", false, "wiretuner.doc.v1.CommonProps", null, null))
        ));
  }

  private static MessagePolicy table_wiretuner_doc_v1_TextWrap() {
    return new MessagePolicy(
        "wiretuner.doc.v1.TextWrap",
        Map.ofEntries(
            Map.entry(1, new FieldPolicy(1, "enabled", Policy.ATOMIC, RefFallback.UNSET, false, "bool", false, null, null, null)),
            Map.entry(2, new FieldPolicy(2, "standoff", Policy.ATOMIC, RefFallback.UNSET, false, "double", false, null, null, null))
        ));
  }

  private static MessagePolicy table_wiretuner_doc_v1_Transform() {
    return new MessagePolicy(
        "wiretuner.doc.v1.Transform",
        Map.ofEntries(
            Map.entry(1, new FieldPolicy(1, "a", Policy.ATOMIC, RefFallback.UNSET, false, "double", false, null, null, null)),
            Map.entry(2, new FieldPolicy(2, "b", Policy.ATOMIC, RefFallback.UNSET, false, "double", false, null, null, null)),
            Map.entry(3, new FieldPolicy(3, "c", Policy.ATOMIC, RefFallback.UNSET, false, "double", false, null, null, null)),
            Map.entry(4, new FieldPolicy(4, "d", Policy.ATOMIC, RefFallback.UNSET, false, "double", false, null, null, null)),
            Map.entry(5, new FieldPolicy(5, "tx", Policy.ATOMIC, RefFallback.UNSET, false, "double", false, null, null, null)),
            Map.entry(6, new FieldPolicy(6, "ty", Policy.ATOMIC, RefFallback.UNSET, false, "double", false, null, null, null))
        ));
  }
}
