// proto/wt/crdt/options.proto
//
// Merge-policy field options for the document schema (docs/spec/crdt-model.adoc, "Merge
// policies").  Every field of every props message in wiretuner.doc.v1 has a merge policy;
// the two defaults (scalars ATOMIC, singular messages STRUCT) cover most fields, so a field
// is annotated only when its default is not what is meant.  protoc-gen-wtcrdt (PROTO-005)
// reads these options and emits the merge tables both engines run on.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: wt/crdt/options.proto

package wtcrdtpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// How concurrent writes to a field are reconciled.
type Merge int32

const (
	// Scalars, strings, bytes, enums and repeated scalars: ATOMIC.
	// Singular message fields: STRUCT.
	Merge_MERGE_UNSPECIFIED Merge = 0
	// The whole value is one register; the op with the greatest OpId wins.
	Merge_MERGE_ATOMIC Merge = 1
	// Each field of the message is its own register (recursively).
	Merge_MERGE_STRUCT Merge = 2
	// A repeated message whose first field is `ElementId id = 1`.  Elements are inserted,
	// moved and deleted individually; order is a fractional position per element (LWW);
	// each element's fields merge as STRUCT.
	Merge_MERGE_SEQUENCE Merge = 3
	// A RichText field: Fugue character sequence plus Peritext formatting marks.
	Merge_MERGE_TEXT Merge = 4
	// A repeated scalar, or a repeated ElementId/OpId, treated as an add-wins observed-remove
	// set; members compare by value.
	Merge_MERGE_SET Merge = 5
	// A message with an enum discriminator (`kind`) and one sibling STRUCT message per case.
	// The discriminator is a register; every case's fields are registers that survive a
	// concurrent kind switch, so switching back restores them.  Preferred over `oneof` for
	// anything users toggle between (fill kinds, effect kinds): a protobuf oneof drops the
	// inactive case and has no defined merge for its discriminator.
	Merge_MERGE_VARIANT Merge = 6
)

// Enum value maps for Merge.
var (
	Merge_name = map[int32]string{
		0: "MERGE_UNSPECIFIED",
		1: "MERGE_ATOMIC",
		2: "MERGE_STRUCT",
		3: "MERGE_SEQUENCE",
		4: "MERGE_TEXT",
		5: "MERGE_SET",
		6: "MERGE_VARIANT",
	}
	Merge_value = map[string]int32{
		"MERGE_UNSPECIFIED": 0,
		"MERGE_ATOMIC":      1,
		"MERGE_STRUCT":      2,
		"MERGE_SEQUENCE":    3,
		"MERGE_TEXT":        4,
		"MERGE_SET":         5,
		"MERGE_VARIANT":     6,
	}
)

func (x Merge) Enum() *Merge {
	p := new(Merge)
	*p = x
	return p
}

func (x Merge) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Merge) Descriptor() protoreflect.EnumDescriptor {
	return file_wt_crdt_options_proto_enumTypes[0].Descriptor()
}

func (Merge) Type() protoreflect.EnumType {
	return &file_wt_crdt_options_proto_enumTypes[0]
}

func (x Merge) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Merge.Descriptor instead.
func (Merge) EnumDescriptor() ([]byte, []int) {
	return file_wt_crdt_options_proto_rawDescGZIP(), []int{0}
}

// What a NodeRef field reads as when the node it points at has been deleted or is unknown.
type RefFallback int32

const (
	// Reference to a deleted or unknown node reads as unset.
	RefFallback_REF_FALLBACK_UNSET RefFallback = 0
	// Read the value cached beside the reference (see NodeRef.cached).
	RefFallback_REF_FALLBACK_CACHED RefFallback = 1
	// The referencing node renders as a placeholder until the reference resolves.
	RefFallback_REF_FALLBACK_PLACEHOLDER RefFallback = 2
)

// Enum value maps for RefFallback.
var (
	RefFallback_name = map[int32]string{
		0: "REF_FALLBACK_UNSET",
		1: "REF_FALLBACK_CACHED",
		2: "REF_FALLBACK_PLACEHOLDER",
	}
	RefFallback_value = map[string]int32{
		"REF_FALLBACK_UNSET":       0,
		"REF_FALLBACK_CACHED":      1,
		"REF_FALLBACK_PLACEHOLDER": 2,
	}
)

func (x RefFallback) Enum() *RefFallback {
	p := new(RefFallback)
	*p = x
	return p
}

func (x RefFallback) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefFallback) Descriptor() protoreflect.EnumDescriptor {
	return file_wt_crdt_options_proto_enumTypes[1].Descriptor()
}

func (RefFallback) Type() protoreflect.EnumType {
	return &file_wt_crdt_options_proto_enumTypes[1]
}

func (x RefFallback) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefFallback.Descriptor instead.
func (RefFallback) EnumDescriptor() ([]byte, []int) {
	return file_wt_crdt_options_proto_rawDescGZIP(), []int{1}
}

// The per-field merge declaration, attached as `[(wt.crdt.field) = {...}]`.
type FieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The merge policy; MERGE_UNSPECIFIED selects the default for the field's type.
	Merge Merge `protobuf:"varint,1,opt,name=merge,proto3,enum=wt.crdt.Merge" json:"merge,omitempty"`
	// For NodeRef fields: what the reference reads as while dangling.
	OnDangling RefFallback `protobuf:"varint,2,opt,name=on_dangling,json=onDangling,proto3,enum=wt.crdt.RefFallback" json:"on_dangling,omitempty"`
	// Never leaves the device: view state stored in the document for convenience.
	LocalOnly     bool `protobuf:"varint,3,opt,name=local_only,json=localOnly,proto3" json:"local_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_wt_crdt_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_wt_crdt_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_wt_crdt_options_proto_rawDescGZIP(), []int{0}
}

func (x *FieldOptions) GetMerge() Merge {
	if x != nil {
		return x.Merge
	}
	return Merge_MERGE_UNSPECIFIED
}

func (x *FieldOptions) GetOnDangling() RefFallback {
	if x != nil {
		return x.OnDangling
	}
	return RefFallback_REF_FALLBACK_UNSET
}

func (x *FieldOptions) GetLocalOnly() bool {
	if x != nil {
		return x.LocalOnly
	}
	return false
}

var file_wt_crdt_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         51234,
		Name:          "wt.crdt.field",
		Tag:           "bytes,51234,opt,name=field",
		Filename:      "wt/crdt/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// The merge declaration for this field.
	//
	// optional wt.crdt.FieldOptions field = 51234;
	E_Field = &file_wt_crdt_options_proto_extTypes[0]
)

var File_wt_crdt_options_proto protoreflect.FileDescriptor

const file_wt_crdt_options_proto_rawDesc = "" +
	"\n" +
	"\x15wt/crdt/options.proto\x12\awt.crdt\x1a google/protobuf/descriptor.proto\"\x8a\x01\n" +
	"\fFieldOptions\x12$\n" +
	"\x05merge\x18\x01 \x01(\x0e2\x0e.wt.crdt.MergeR\x05merge\x125\n" +
	"\von_dangling\x18\x02 \x01(\x0e2\x14.wt.crdt.RefFallbackR\n" +
	"onDangling\x12\x1d\n" +
	"\n" +
	"local_only\x18\x03 \x01(\bR\tlocalOnly*\x88\x01\n" +
	"\x05Merge\x12\x15\n" +
	"\x11MERGE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fMERGE_ATOMIC\x10\x01\x12\x10\n" +
	"\fMERGE_STRUCT\x10\x02\x12\x12\n" +
	"\x0eMERGE_SEQUENCE\x10\x03\x12\x0e\n" +
	"\n" +
	"MERGE_TEXT\x10\x04\x12\r\n" +
	"\tMERGE_SET\x10\x05\x12\x11\n" +
	"\rMERGE_VARIANT\x10\x06*\\\n" +
	"\vRefFallback\x12\x16\n" +
	"\x12REF_FALLBACK_UNSET\x10\x00\x12\x17\n" +
	"\x13REF_FALLBACK_CACHED\x10\x01\x12\x1c\n" +
	"\x18REF_FALLBACK_PLACEHOLDER\x10\x02:L\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xa2\x90\x03 \x01(\v2\x15.wt.crdt.FieldOptionsR\x05fieldB'\n" +
	"!com.villagecompute.wiretuner.crdtH\x01P\x01b\x06proto3"

var (
	file_wt_crdt_options_proto_rawDescOnce sync.Once
	file_wt_crdt_options_proto_rawDescData []byte
)

func file_wt_crdt_options_proto_rawDescGZIP() []byte {
	file_wt_crdt_options_proto_rawDescOnce.Do(func() {
		file_wt_crdt_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wt_crdt_options_proto_rawDesc), len(file_wt_crdt_options_proto_rawDesc)))
	})
	return file_wt_crdt_options_proto_rawDescData
}

var file_wt_crdt_options_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_wt_crdt_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wt_crdt_options_proto_goTypes = []any{
	(Merge)(0),                        // 0: wt.crdt.Merge
	(RefFallback)(0),                  // 1: wt.crdt.RefFallback
	(*FieldOptions)(nil),              // 2: wt.crdt.FieldOptions
	(*descriptorpb.FieldOptions)(nil), // 3: google.protobuf.FieldOptions
}
var file_wt_crdt_options_proto_depIdxs = []int32{
	0, // 0: wt.crdt.FieldOptions.merge:type_name -> wt.crdt.Merge
	1, // 1: wt.crdt.FieldOptions.on_dangling:type_name -> wt.crdt.RefFallback
	3, // 2: wt.crdt.field:extendee -> google.protobuf.FieldOptions
	2, // 3: wt.crdt.field:type_name -> wt.crdt.FieldOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	3, // [3:4] is the sub-list for extension type_name
	2, // [2:3] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wt_crdt_options_proto_init() }
func file_wt_crdt_options_proto_init() {
	if File_wt_crdt_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wt_crdt_options_proto_rawDesc), len(file_wt_crdt_options_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_wt_crdt_options_proto_goTypes,
		DependencyIndexes: file_wt_crdt_options_proto_depIdxs,
		EnumInfos:         file_wt_crdt_options_proto_enumTypes,
		MessageInfos:      file_wt_crdt_options_proto_msgTypes,
		ExtensionInfos:    file_wt_crdt_options_proto_extTypes,
	}.Build()
	File_wt_crdt_options_proto = out.File
	file_wt_crdt_options_proto_goTypes = nil
	file_wt_crdt_options_proto_depIdxs = nil
}
