/// WTCRDTSchema: the merge table generated by `protoc-gen-wtcrdt` (PROTO-004) lands in
/// `Generated/`.  This file only keeps the target buildable while that directory is empty.
public enum WTCRDTSchemaPackage {
    public static let name = "WTCRDTSchema"
}
