import Foundation

/// WTCRDTSchema: the merge table and validators generated by `protoc-gen-wtcrdt` (PROTO-005)
/// into `Generated/` (`WTMergeTable`, `WTValidators`).  Regenerate with
/// `make -C tools/protoc-gen-wtcrdt generate`; never edit `Generated/` by hand.
public enum WTCRDTSchemaPackage {
    public static let name = "WTCRDTSchema"

    /// The bundled `MergeTable.json`, byte for byte what `WTMergeTable.json` holds.
    public static func mergeTableResource() -> Data? {
        guard let url = Bundle.module.url(forResource: "MergeTable", withExtension: "json") else {
            return nil
        }
        return try? Data(contentsOf: url)
    }
}
