// FONT-019: `FeatureGenerator` (opentype-features.adoc, "Features generated automatically" and
// "Data model"): the automatic features as feature text, produced from the compiler's input at
// every compile and never stored -- `kern` from the kerning (named classes `@kern1.<name>` /
// `@kern2.<name>`, a repeated name written `<name>_2` in class order; pair kerns before class
// kerns so they win), `mark` and `mkmk` from anchors (`top` on bases, `_top` on marks), `liga`
// from Ligature-kind glyphs named by their parts (longer first), and the `GDEF` glyph classes from
// the kinds.  Glyphs are taken in glyph order and classes in the order given (element-id order),
// so two clients generate byte-identical text.  `file(user:generated:)` assembles the text the
// compiler reads: a default `languagesystem` when the user's text has none, the user's text, the
// marker line, then the generated text.

/// Produces the generated feature text.
public enum FeatureGenerator {
    /// The line between the user's text and the generated text.
    public static let marker = "# ---- generated by WireTuner: do not edit (regenerated on every build) ----"

    /// Words the grammar reads as keywords: a glyph with one of these names is written `\name`.
    static let keywords: Set<String> = [
        "sub", "substitute", "pos", "position", "by", "from", "lookup", "feature", "languagesystem", "script", "language", "markClass", "mark",
        "base", "ligature", "cursive", "enum", "enumerate", "ignore", "lookupflag", "table", "subtable", "anchor", "NULL", "useExtension",
        "exclude_dflt", "include_dflt", "excludeDFLT", "includeDFLT", "RightToLeft", "IgnoreBaseGlyphs", "IgnoreLigatures", "IgnoreMarks",
        "GlyphClassDef", "rsub", "reversesub", "include", "parameters", "featureNames", "anonymous", "anon",
    ]

    /// The assembled feature file and where its parts start (1-based lines).
    public struct File: Hashable, Sendable {
        public var text: String
        /// The line of the full text holding the user's first line.
        public var userFirstLine: Int
        /// The first line of the generated part (the marker's line), or nil when nothing is
        /// generated.
        public var generatedFirstLine: Int?

        /// Maps a location in the full text back to the user's text; nil for the generated part
        /// or the added `languagesystem` line.
        public func userLocation(_ location: FeatureLocation) -> FeatureLocation? {
            guard location.line >= userFirstLine, generatedFirstLine.map({ location.line < $0 }) ?? true else { return nil }
            return FeatureLocation(line: location.line - userFirstLine + 1, column: location.column)
        }
    }

    /// The full text: `user` then `generated`.
    public static func file(user: String, generated: String) -> File {
        let addsSystem = !FeatureLexer.tokens(user).contains { $0.kind == .name("languagesystem", escaped: false) }
        var text = addsSystem ? "languagesystem DFLT dflt;\n" : ""
        let userFirstLine = addsSystem ? 2 : 1
        text += user
        guard !generated.isEmpty else { return File(text: text, userFirstLine: userFirstLine, generatedFirstLine: nil) }
        if !user.isEmpty, !user.hasSuffix("\n") { text += "\n" }
        let generatedFirstLine = text.reduce(1) { $1 == "\n" ? $0 + 1 : $0 }
        text += marker + "\n" + generated
        return File(text: text, userFirstLine: userFirstLine, generatedFirstLine: generatedFirstLine)
    }

    /// The tags `generated(_:)` defines for `source`.
    public static func generatedTags(_ source: FontSource) -> Set<String> {
        var tags: Set<String> = []
        if !kern(source).isEmpty { tags.insert("kern") }
        let marks = markText(source)
        if !marks.mark.isEmpty { tags.insert("mark") }
        if !marks.mkmk.isEmpty { tags.insert("mkmk") }
        if !liga(source).isEmpty { tags.insert("liga") }
        return tags
    }

    /// The generated text for `source` (empty when there is nothing to generate).
    public static func generated(_ source: FontSource) -> String {
        let marks = markText(source)
        return [kern(source), marks.classes, marks.mark, marks.mkmk, liga(source), gdef(source)].filter { !$0.isEmpty }.joined()
    }

    /// A glyph name as written: `\name` for keywords and names that would not read as one name.
    public static func glyph(_ name: String) -> String {
        let scalars = Array(name.unicodeScalars)
        let plain = !keywords.contains(name) && !scalars.isEmpty && FeatureLexer.nameStart.contains(scalars[0])
            && scalars.allSatisfy(FeatureLexer.nameBody.contains)
        return plain ? name : "\\" + name
    }

    /// `name` reduced to the characters a class or lookup name may hold.
    static func identifier(_ name: String) -> String {
        let scalars = name.unicodeScalars.map { FeatureLexer.nameBody.contains($0) && $0 != "-" ? Character($0) : "_" }
        return scalars.isEmpty ? "class" : String(scalars)
    }

    /// Names made unique in order: the second `O` is `O_2`.
    static func unique(_ names: [String]) -> [String] {
        var used: Set<String> = []
        return names.map { name in
            var candidate = name
            var suffix = 2
            while used.contains(candidate) {
                candidate = "\(name)_\(suffix)"
                suffix += 1
            }
            used.insert(candidate)
            return candidate
        }
    }

    // MARK: Features

    static func kern(_ source: FontSource) -> String {
        let kerning = source.kerning
        let count = source.glyphs.count
        func name(_ index: Int) -> String { glyph(source.glyphs[index].name) }
        func classes(_ members: [[Int]], names: [String], prefix: String) -> (names: [String?], text: String) {
            let kept = members.map { $0.filter { $0 < count } }
            let base = kept.enumerated().map { offset, glyphs -> String in
                let given = offset < names.count ? names[offset] : ""
                return identifier(given.isEmpty ? (glyphs.first.map { source.glyphs[$0].name } ?? "class") : given)
            }
            let uniqueNames = unique(base)
            var text = ""
            var result: [String?] = []
            for (offset, glyphs) in kept.enumerated() {
                guard !glyphs.isEmpty else {
                    result.append(nil)
                    continue
                }
                let written = "@\(prefix).\(uniqueNames[offset])"
                result.append(written)
                text += "\(written) = [\(glyphs.map(name).joined(separator: " "))];\n"
            }
            return (result, text)
        }
        let left = classes(kerning.leftClasses, names: kerning.leftClassNames, prefix: "kern1")
        let right = classes(kerning.rightClasses, names: kerning.rightClassNames, prefix: "kern2")
        var rules = ""
        var seen: Set<[Int]> = []
        for pair in kerning.pairs.sorted(by: { ($0.left, $0.right) < ($1.left, $1.right) })
        where pair.left < count && pair.right < count && seen.insert([pair.left, pair.right]).inserted {
            rules += "    pos \(name(pair.left)) \(name(pair.right)) \(pair.value);\n"
        }
        seen = []
        for cell in kerning.classValues.sorted(by: { ($0.left, $0.right) < ($1.left, $1.right) }) {
            guard left.names.indices.contains(cell.left), right.names.indices.contains(cell.right), let l = left.names[cell.left], let r = right.names[cell.right],
                  seen.insert([cell.left, cell.right]).inserted else { continue }
            rules += "    pos \(l) \(r) \(cell.value);\n"
        }
        guard !rules.isEmpty else { return "" }
        return left.text + right.text + "feature kern {\n" + rules + "} kern;\n"
    }

    static func markText(_ source: FontSource) -> (classes: String, mark: String, mkmk: String) {
        guard source.generateMark else { return ("", "", "") }
        func anchor(_ anchor: FontSource.Anchor) -> String { "<anchor \(Int(anchor.x.rounded())) \(Int(anchor.y.rounded()))>" }
        func first(_ glyph: FontSource.Glyph, _ name: String) -> FontSource.Anchor? { glyph.anchors.first { $0.name == name } }
        let marks = source.glyphs.filter { $0.kind == .mark }
        let attachmentNames = Set(marks.flatMap { $0.anchors.map(\.name) }.filter { $0.hasPrefix("_") && $0.count > 1 }.map { String($0.dropFirst()) }).sorted()
        var classes = "", mark = "", mkmk = ""
        let classNames = unique(attachmentNames.map { "MC_" + identifier($0) })
        for (name, className) in zip(attachmentNames, classNames) {
            let members = marks.filter { first($0, "_" + name) != nil }
            let bases = source.glyphs.filter { $0.kind != .mark && $0.name != ".notdef" && first($0, name) != nil }
            let stacking = members.filter { first($0, name) != nil }
            guard !bases.isEmpty || !stacking.isEmpty else { continue }
            for member in members { classes += "markClass \(glyph(member.name)) \(anchor(first(member, "_" + name)!)) @\(className);\n" }
            let lookup = identifier(name)
            if !bases.isEmpty {
                mark += "    lookup mark_\(lookup) {\n"
                for base in bases { mark += "        pos base \(glyph(base.name)) \(anchor(first(base, name)!)) mark @\(className);\n" }
                mark += "    } mark_\(lookup);\n"
            }
            if !stacking.isEmpty {
                mkmk += "    lookup mkmk_\(lookup) {\n"
                for base in stacking { mkmk += "        pos mark \(glyph(base.name)) \(anchor(first(base, name)!)) mark @\(className);\n" }
                mkmk += "    } mkmk_\(lookup);\n"
            }
        }
        return (classes, mark.isEmpty ? "" : "feature mark {\n" + mark + "} mark;\n", mkmk.isEmpty ? "" : "feature mkmk {\n" + mkmk + "} mkmk;\n")
    }

    static func liga(_ source: FontSource) -> String {
        guard source.generateLiga else { return "" }
        let names = Set(source.glyphs.map(\.name))
        let rules = source.glyphs.enumerated().compactMap { offset, glyph -> (parts: [String], name: String, order: Int)? in
            guard glyph.kind == .ligature, !glyph.name.contains(".") else { return nil }
            let parts = glyph.name.split(separator: "_", omittingEmptySubsequences: false).map(String.init)
            guard parts.count > 1, parts.allSatisfy({ !$0.isEmpty && names.contains($0) && $0 != glyph.name }) else { return nil }
            return (parts, glyph.name, offset)
        }.sorted { ($1.parts.count, $0.order) < ($0.parts.count, $1.order) }
        guard !rules.isEmpty else { return "" }
        return "feature liga {\n" + rules.map { "    sub \($0.parts.map(glyph).joined(separator: " ")) by \(glyph($0.name));\n" }.joined() + "} liga;\n"
    }

    static func gdef(_ source: FontSource) -> String {
        guard source.glyphs.contains(where: { $0.kind != .base }) else { return "" }
        let sets = FontSource.GlyphKind.allCases.map { kind in
            let members = source.glyphs.filter { $0.kind == kind && $0.name != ".notdef" }.map { glyph($0.name) }
            return members.isEmpty ? "" : "[\(members.joined(separator: " "))]"
        }
        return "table GDEF {\n    GlyphClassDef \(sets.joined(separator: ", "));\n} GDEF;\n"
    }
}
