import Foundation
import SwiftProtobuf
import Testing
@testable import WTCRDT
import WTProto

/// The cross-engine fuzzer (CRDT-012; docs/spec/testing.adoc, "Fuzzing").  WTCRDT generates the
/// vectors (`FuzzGenerator`), replays every delivery of each, records the hashes it reached and,
/// when `WT_FUZZ_CORPUS` names a directory, writes the corpus there for wt-crdt to replay
/// (server/conformance's `FuzzCorpusTest`); `make -C crdt-conformance fuzz` runs both.  A vector
/// on which WTCRDT's deliveries disagree is minimised here; one on which wt-crdt disagrees with
/// the recorded hashes is minimised by `crossEngineMinimisation` with the Java oracle.
///
/// Environment: `WT_FUZZ_OPS` (default 20,000; the nightly run takes 1,000,000), `WT_FUZZ_SEED`
/// (default 1), `WT_FUZZ_ROUND_OPS` (ops per vector, default 250), `WT_FUZZ_CORPUS`.
@Suite struct FuzzTests {
    static let environment = ProcessInfo.processInfo.environment

    /// What a run found.
    struct Run {
        var vectors = 0
        var ops = 0
        var collections = 0
        var failures: [String] = []
    }

    /// The seed of vector `index` of a run seeded with `seed`: one SplitMix64 step apart, so any
    /// vector regenerates on its own.
    static func roundSeed(_ seed: UInt64, _ index: Int) -> UInt64 {
        var mix = SplitMix64(seed: seed ^ (UInt64(index) &* 0x9E37_79B9_7F4A_7C15))
        return mix.next()
    }

    /// The name of vector `index`: its path below the corpus root.
    static func name(_ seed: UInt64, _ index: Int) -> String {
        String(format: "fuzz/%016llx-%06d", seed, index)
    }

    /// Generates and replays `ops` ops in vectors of `roundOps`, writing each into `corpus`.
    static func run(ops: Int, seed: UInt64, roundOps: Int, corpus: URL?, minimized: URL) throws -> Run {
        var run = Run()
        let schema = Scenario.schema
        while run.ops < ops {
            let name = name(seed, run.vectors)
            var generator = FuzzGenerator(seed: roundSeed(seed, run.vectors))
            var (vector, summary) = generator.vector(name: name, ops: min(roundOps, ops - run.ops), schema: schema)
            run.vectors += 1
            run.ops += summary.ops
            run.collections += summary.collections
            let outcome = ConformanceRunner.run(vector, expectedName: name, expectations: false)
            if !outcome.passed {
                let small = FuzzMinimizer.minimize(vector) { !ConformanceRunner.run($0, expectedName: name, expectations: false).passed }
                let file = try write(small, below: minimized)
                run.failures.append("\(outcome.report)\n  minimised: \(file.path)")
                continue
            }
            if let stray = summary.replicaHashes.first(where: { $0 != outcome.stateHash }) {
                run.failures.append("\(name): a simulated replica ended at \(stray), its delivery at \(outcome.stateHash)")
            }
            vector.expect.stateHash = outcome.stateHash
            vector.expect.snapshotHash = outcome.snapshotHash
            if let corpus {
                _ = try write(vector, below: corpus)
            }
        }
        return run
    }

    /// Writes `vector` to `<root>/<name>.textproto`.
    @discardableResult
    static func write(_ vector: FuzzGenerator.Vector, below root: URL) throws -> URL {
        let file = root.appendingPathComponent(vector.name + ConformanceRunner.suffix)
        try FileManager.default.createDirectory(at: file.deletingLastPathComponent(), withIntermediateDirectories: true)
        try ("# Generated by the CRDT-012 fuzzer (docs/spec/testing.adoc, \"Fuzzing\").\n" + vector.textFormatString())
            .write(to: file, atomically: true, encoding: .utf8)
        return file
    }

    @Test func generatedVectorsConvergeInWTCRDT() throws {
        let ops = Int(Self.environment["WT_FUZZ_OPS"] ?? "") ?? 20_000
        let seed = UInt64(Self.environment["WT_FUZZ_SEED"] ?? "") ?? 1
        let roundOps = Int(Self.environment["WT_FUZZ_ROUND_OPS"] ?? "") ?? 250
        let corpus = Self.environment["WT_FUZZ_CORPUS"].map { URL(fileURLWithPath: $0) }
        let minimized = corpus.map { URL(fileURLWithPath: $0.path + "-minimized") }
            ?? FileManager.default.temporaryDirectory.appendingPathComponent("wtcrdt-fuzz-minimized")
        let started = Date()
        let run = try Self.run(ops: ops, seed: seed, roundOps: roundOps, corpus: corpus, minimized: minimized)
        print(String(format: "Fuzz (WTCRDT): %d ops in %d vectors, %d collections, seed %llu, %.1f s",
                     run.ops, run.vectors, run.collections, seed, Date().timeIntervalSince(started)))
        #expect(run.ops >= ops)
        #expect(run.failures.isEmpty, "\(run.failures.joined(separator: "\n"))")
    }

    @Test func aSeedAlwaysWritesTheSameVectorAndTheVectorPassesAsWritten() throws {
        var first = FuzzGenerator(seed: 42)
        var second = FuzzGenerator(seed: 42)
        let a = first.vector(name: "fuzz/a", ops: 120, schema: Scenario.schema).vector
        let b = second.vector(name: "fuzz/a", ops: 120, schema: Scenario.schema).vector
        #expect(a == b)
        let outcome = ConformanceRunner.run(a, expectedName: "fuzz/a", expectations: false)
        #expect(outcome.passed, "\(outcome.report)")
        var recorded = a
        recorded.expect.stateHash = outcome.stateHash
        recorded.expect.snapshotHash = outcome.snapshotHash
        let text = try FuzzGenerator.Vector(textFormatString: recorded.textFormatString())
        #expect(ConformanceRunner.run(text, expectedName: "fuzz/a").passed)
        #expect(a.deliveries.count == a.replica.count + 1 && a.deliveries.contains { !$0.collect.isEmpty })
        let run = try Self.run(ops: 300, seed: 7, roundOps: 150, corpus: nil, minimized: FileManager.default.temporaryDirectory)
        #expect(run.vectors == 2 && run.failures.isEmpty)
    }

    @Test func ddminFindsTheSmallestFailingSubset() {
        #expect(FuzzMinimizer.ddmin(Array(0..<20)) { $0.contains(3) && $0.contains(17) } == [3, 17])
        #expect(FuzzMinimizer.ddmin(Array(0..<5)) { _ in true } == [])
        #expect(FuzzMinimizer.ddmin(Array(0..<5), minimum: 1) { _ in true }.count == 1)
        #expect(FuzzMinimizer.ddmin(Array(0..<5)) { $0.count == 5 } == Array(0..<5))
    }

    @Test func theMinimiserShrinksAVectorToTheChangeThatFails() throws {
        var generator = FuzzGenerator(seed: 3)
        let vector = generator.vector(name: "fuzz/m", ops: 80, schema: Scenario.schema).vector
        let changes = vector.replica.flatMap { replica in replica.change.map { FuzzMinimizer.Key(replica: replica.id, seq: $0.seq) } }
        let culprit = changes[changes.count / 2]
        let small = FuzzMinimizer.minimize(vector) { candidate in
            candidate.replica.contains { replica in replica.id == culprit.replica && replica.change.contains { $0.seq == culprit.seq } }
                && candidate.deliveries.contains { $0.picks.contains { $0.replica == culprit.replica && $0.seq == culprit.seq } }
        }
        #expect(small.replica.count == 1 && small.replica[0].change.count == 1 && small.deliveries.count == 1)
        #expect(small.deliveries.allSatisfy { $0.collect.isEmpty })
        #expect(small.replica[0].change[0].ops.allSatisfy(FuzzMinimizer.isNoop))
        #expect(small.deliveries[0].picks.allSatisfy { $0.replica == culprit.replica && $0.seq == culprit.seq })
        // Dropping changes keeps each collection after the picks that remain before it.
        let kept = FuzzMinimizer.keeping(vector, changes: [])
        #expect(kept.deliveries.allSatisfy { delivery in delivery.picks.isEmpty && delivery.collect.allSatisfy { $0.after == 0 } })
    }

    /// Minimises each vector wt-crdt disagreed on (`WT_FUZZ_MINIMIZE`, paths separated by `:`)
    /// against the Java oracle (`WT_FUZZ_ORACLE`, a command given the candidate's path, exiting
    /// non-zero when wt-crdt does not reach the hashes WTCRDT recorded), into `<corpus>-minimized`.
    @Test(.enabled(if: environment["WT_FUZZ_MINIMIZE"] != nil && environment["WT_FUZZ_ORACLE"] != nil))
    func crossEngineMinimisation() throws {
        let oracle = Self.environment["WT_FUZZ_ORACLE"]!
        let scratch = FileManager.default.temporaryDirectory.appendingPathComponent("wtcrdt-fuzz-oracle-\(getpid())")
        for path in Self.environment["WT_FUZZ_MINIMIZE"]!.split(separator: ":").map(String.init) {
            let vector = try FuzzGenerator.Vector(textFormatString: String(contentsOfFile: path, encoding: .utf8))
            func recorded(_ candidate: FuzzGenerator.Vector) -> FuzzGenerator.Vector? {
                let outcome = ConformanceRunner.run(candidate, expectedName: candidate.name, expectations: false)
                guard outcome.passed else { return nil }
                var out = candidate
                out.expect.stateHash = outcome.stateHash
                out.expect.snapshotHash = outcome.snapshotHash
                return out
            }
            func javaDisagrees(_ candidate: FuzzGenerator.Vector) -> Bool {
                guard let candidate = recorded(candidate), let file = try? Self.write(candidate, below: scratch) else { return false }
                let process = Process()
                process.executableURL = URL(fileURLWithPath: "/bin/sh")
                process.arguments = ["-c", "\(oracle) '\(file.path)'"]
                process.standardOutput = FileHandle.nullDevice
                process.standardError = FileHandle.nullDevice
                guard (try? process.run()) != nil else { return false }
                process.waitUntilExit()
                return process.terminationStatus != 0
            }
            #expect(javaDisagrees(vector), "\(path): wt-crdt agrees with WTCRDT")
            let small = recorded(FuzzMinimizer.minimize(vector, fails: javaDisagrees))!
            let root = URL(fileURLWithPath: path).deletingLastPathComponent().deletingLastPathComponent()
            let file = try Self.write(small, below: URL(fileURLWithPath: root.path + "-minimized"))
            print("Fuzz: \(path) minimised to \(file.path)")
        }
    }
}
